// importIdentity.js
const fs = require('fs');
const path = require('path');
const { Wallets } = require('fabric-network');

async function main() {
  const wallet = await Wallets.newFileSystemWallet(path.join(__dirname, 'wallet'));

  // paths to Org1 admin cert & key (generated by test-network)
  const mspPath = path.resolve(__dirname, '..', 'test-network', 'organizations', 'peerOrganizations', 'org1.example.com', 'users', 'Admin@org1.example.com', 'msp');
  const certPath = path.join(mspPath, 'signcerts', 'cert.pem');

  const keyFolder = path.join(mspPath, 'keystore');
  const keyFiles = fs.readdirSync(keyFolder);
  const keyPath = path.join(keyFolder, keyFiles[0]);

  const cert = fs.readFileSync(certPath).toString();
  const key = fs.readFileSync(keyPath).toString();

  const identityLabel = 'admin'; // will be the identity name used by app.js (getContractForUser('admin'))

  const identity = {
    credentials: {
      certificate: cert,
      privateKey: key,
    },
    mspId: 'Org1MSP',
    type: 'X.509',
  };

  await wallet.put(identityLabel, identity);
  console.log(`Successfully imported identity ${identityLabel} into wallet`);
}

main().catch(err => { console.error(err); process.exit(1); });
